---
- name: Install Apache and starts the service
  hosts: webserver
  tasks:
    - name: 1) 패키지 설치
      ansible.builtin.yum:
        name: "{{ ansible_local.custom.general.package }}"
        state: present

    - name: 2) 서비스 기동
      ansible.builtin.service:
        name: "{{ ansible_local.custom.general.service }}"
        state: "{{ ansible_local.custom.general.state }}"
        enabled: true

    - name: 2) 서비스 기동
      ansible.builtin.service:
        name: firewalld
        state: started
        enabled: true

    - name: 3) 방화벽 포트 설정
      ansible.posix.firewalld:
        service: "{{ ansible_local.custom.general.fwsvc }}"
        permanent: true
        immediate: true
        state: enabled
