---
- name: Restore playbook.yml
  hosts: all
  gather_facts: true
  vars_files:
    - vars/vars.yml
  tasks:
    - name: 1) 방화벽에 포트 제거
      ansible.posix.firewalld:
        service: "{{ item }}"
        permanent: true
        immediate: true
        state: disabled
      loop: "{{ firewall_rules }}"

    - name: 2) 서비스 종료 - {{ services }}
      ansible.builtin.systemd:
        name: "{{ item }}"
        enabled: false
        state: stopped
      loop: "{{ services }}"

    - name: 3) 웹 서비스 설정 삭제
      ansible.builtin.file:
        path: /var/www/html/index.html  # 별도로 만든 것만 삭제
        state: absent

    - name: 4) 패키지 삭제 - {{ packages }}
      ansible.builtin.dnf:
        name:
          - httpd
          - mod_ssl
        state: absent
