---
# Task File:
- name: 서비스 종료 - {{ service }}
  ansible.builtin.systemd:
    name: "{{ service }}"
    enabled: false
    state: stopped

- name: 설정 파일 삭제 - {{ files }}
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop: "{{ files }}"

- name: 패키지 설치 - {{ packages }}
  ansible.builtin.dnf:
    name: "{{ packages }}"
    state: absent

