---
- name: Restore playbook.yml
  hosts: databases
  vars:
    db_packages:
      - mariadb-server
      - python3-PyMySQL
    db_service: mariadb
  tasks:
    - name: 0) DB 서비스 중지
      ansible.builtin.service:
        name: "{{ db_service }}"
        state: stopped
        enabled: false

    - name: "1) 패키지 삭제"
      ansible.builtin.yum:
        name: "{{ db_packages }}"
        state: absent
